// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pythonenv} from '../models';
import {logs} from '../models';
import {sandbox} from '../models';
import {theory} from '../models';
import {accounts} from '../models';
import {tasks} from '../models';
import {combat} from '../models';

export function Accounts():Promise<any>;

export function ArenaTrack():Promise<any>;

export function CombatTrack():Promise<any>;

export function DashboardSummary():Promise<any>;

export function DeleteAccount(arg1:number):Promise<void>;

export function ExportMigrationBundle():Promise<any>;

export function Health():Promise<any>;

export function InitializePythonEnv(arg1:pythonenv.InitRequest):Promise<any>;

export function InstallPythonPackages(arg1:pythonenv.InstallPackagesRequest):Promise<any>;

export function LogContent(arg1:logs.ContentRequest):Promise<any>;

export function Logs():Promise<any>;

export function NetworkProxy():Promise<any>;

export function Overview():Promise<any>;

export function PracticeTrack():Promise<any>;

export function PythonEnvStatus():Promise<any>;

export function RefreshCombatTrack():Promise<any>;

export function RunPythonSandbox(arg1:sandbox.RunRequest):Promise<any>;

export function RunTheoryAutomation(arg1:theory.AutomationRequest):Promise<any>;

export function SandboxProfiles():Promise<any>;

export function SaveAccount(arg1:accounts.Account):Promise<any>;

export function SaveNetworkProxy(arg1:tasks.NetworkProxySettings):Promise<any>;

export function SaveTheoryAISettings(arg1:theory.AISettings):Promise<any>;

export function SaveTheoryReview(arg1:theory.ReviewDecision):Promise<any>;

export function SearchTheoryBank(arg1:string):Promise<any>;

export function StartTask(arg1:tasks.StartRequest):Promise<any>;

export function StartTheoryAIReview(arg1:theory.AIReviewRequest):Promise<any>;

export function StartTheoryAutomation(arg1:theory.AutomationRequest):Promise<any>;

export function StopAllTasks():Promise<any>;

export function StopTask(arg1:string):Promise<any>;

export function StopTheoryAIReview():Promise<any>;

export function StopTheoryAutomation():Promise<any>;

export function SubmitCombat(arg1:combat.SubmitRequest):Promise<any>;

export function SubmitTheoryManual(arg1:theory.ManualSubmitRequest):Promise<any>;

export function SyncWriteups():Promise<any>;

export function Tasks():Promise<any>;

export function TestTheoryAISettings(arg1:theory.AISettings):Promise<any>;

export function TheoryAIReviewStatus():Promise<any>;

export function TheoryAISettings():Promise<any>;

export function TheoryAutomationStatus():Promise<any>;

export function TheoryReviewItems():Promise<any>;

export function TheoryTrack():Promise<any>;

export function TheoryTrackWithRequest(arg1:theory.SnapshotRequest):Promise<any>;

export function Writeups():Promise<any>;
