// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Accounts() {
  return window['go']['desktop']['API']['Accounts']();
}

export function ArenaTrack() {
  return window['go']['desktop']['API']['ArenaTrack']();
}

export function CombatTrack() {
  return window['go']['desktop']['API']['CombatTrack']();
}

export function DashboardSummary() {
  return window['go']['desktop']['API']['DashboardSummary']();
}

export function DeleteAccount(arg1) {
  return window['go']['desktop']['API']['DeleteAccount'](arg1);
}

export function ExportMigrationBundle() {
  return window['go']['desktop']['API']['ExportMigrationBundle']();
}

export function Health() {
  return window['go']['desktop']['API']['Health']();
}

export function InitializePythonEnv(arg1) {
  return window['go']['desktop']['API']['InitializePythonEnv'](arg1);
}

export function InstallPythonPackages(arg1) {
  return window['go']['desktop']['API']['InstallPythonPackages'](arg1);
}

export function LogContent(arg1) {
  return window['go']['desktop']['API']['LogContent'](arg1);
}

export function Logs() {
  return window['go']['desktop']['API']['Logs']();
}

export function NetworkProxy() {
  return window['go']['desktop']['API']['NetworkProxy']();
}

export function Overview() {
  return window['go']['desktop']['API']['Overview']();
}

export function PracticeTrack() {
  return window['go']['desktop']['API']['PracticeTrack']();
}

export function PythonEnvStatus() {
  return window['go']['desktop']['API']['PythonEnvStatus']();
}

export function RefreshCombatTrack() {
  return window['go']['desktop']['API']['RefreshCombatTrack']();
}

export function RunPythonSandbox(arg1) {
  return window['go']['desktop']['API']['RunPythonSandbox'](arg1);
}

export function RunTheoryAutomation(arg1) {
  return window['go']['desktop']['API']['RunTheoryAutomation'](arg1);
}

export function SandboxProfiles() {
  return window['go']['desktop']['API']['SandboxProfiles']();
}

export function SaveAccount(arg1) {
  return window['go']['desktop']['API']['SaveAccount'](arg1);
}

export function SaveNetworkProxy(arg1) {
  return window['go']['desktop']['API']['SaveNetworkProxy'](arg1);
}

export function SaveTheoryAISettings(arg1) {
  return window['go']['desktop']['API']['SaveTheoryAISettings'](arg1);
}

export function SaveTheoryReview(arg1) {
  return window['go']['desktop']['API']['SaveTheoryReview'](arg1);
}

export function SearchTheoryBank(arg1) {
  return window['go']['desktop']['API']['SearchTheoryBank'](arg1);
}

export function StartTask(arg1) {
  return window['go']['desktop']['API']['StartTask'](arg1);
}

export function StartTheoryAIReview(arg1) {
  return window['go']['desktop']['API']['StartTheoryAIReview'](arg1);
}

export function StartTheoryAutomation(arg1) {
  return window['go']['desktop']['API']['StartTheoryAutomation'](arg1);
}

export function StopAllTasks() {
  return window['go']['desktop']['API']['StopAllTasks']();
}

export function StopTask(arg1) {
  return window['go']['desktop']['API']['StopTask'](arg1);
}

export function StopTheoryAIReview() {
  return window['go']['desktop']['API']['StopTheoryAIReview']();
}

export function StopTheoryAutomation() {
  return window['go']['desktop']['API']['StopTheoryAutomation']();
}

export function SubmitCombat(arg1) {
  return window['go']['desktop']['API']['SubmitCombat'](arg1);
}

export function SubmitTheoryManual(arg1) {
  return window['go']['desktop']['API']['SubmitTheoryManual'](arg1);
}

export function SyncWriteups() {
  return window['go']['desktop']['API']['SyncWriteups']();
}

export function Tasks() {
  return window['go']['desktop']['API']['Tasks']();
}

export function TestTheoryAISettings(arg1) {
  return window['go']['desktop']['API']['TestTheoryAISettings'](arg1);
}

export function TheoryAIReviewStatus() {
  return window['go']['desktop']['API']['TheoryAIReviewStatus']();
}

export function TheoryAISettings() {
  return window['go']['desktop']['API']['TheoryAISettings']();
}

export function TheoryAutomationStatus() {
  return window['go']['desktop']['API']['TheoryAutomationStatus']();
}

export function TheoryReviewItems() {
  return window['go']['desktop']['API']['TheoryReviewItems']();
}

export function TheoryTrack() {
  return window['go']['desktop']['API']['TheoryTrack']();
}

export function TheoryTrackWithRequest(arg1) {
  return window['go']['desktop']['API']['TheoryTrackWithRequest'](arg1);
}

export function Writeups() {
  return window['go']['desktop']['API']['Writeups']();
}
